import { Match } from '../../shared/models';

export const matches: Match[] = [
    {
        id: 1,
        homeTeamName: 'Сятра',
        homeTeamLogoUrl: 'images/teams/sytra_logo.svg',
        homeTeamScore: 4,
        awayTeamName: 'Шоркино',
        awayTeamLogoUrl: 'images/teams/shorkino.png',
        awayTeamScore: 2,
        matchDateTime: '14 июня, 18:00',
        seasonYear: 2025,
        roundNumber: 1,
        venueName: 'Стадион «Трёхэтажка»',
    },
    {
        id: 2,
        homeTeamName: 'Сарбаки',
        homeTeamLogoUrl: 'images/teams/sarbaki.svg',
        homeTeamScore: 0,
        awayTeamName: 'Побои',
        awayTeamLogoUrl: 'images/teams/poboi.svg',
        awayTeamScore: 1,
        matchDateTime: '14 июня, 19:00',
        seasonYear: 2025,
        roundNumber: 1,
        venueName: 'Стадион «Трёхэтажка»',
    },
    {
        id: 3,
        homeTeamName: 'Сарбаки',
        homeTeamLogoUrl: 'images/teams/sarbaki.svg',
        homeTeamScore: 3,
        awayTeamName: 'Шоркино',
        awayTeamLogoUrl: 'images/teams/shorkino.png',
        awayTeamScore: 1,
        matchDateTime: '21 июня, 18:00',
        seasonYear: 2025,
        roundNumber: 2,
        venueName: 'Стадион «Трёхэтажка»',
    },
    {
        id: 4,
        homeTeamName: 'Сятра',
        homeTeamLogoUrl: 'images/teams/sytra_logo.svg',
        homeTeamScore: 0,
        awayTeamName: 'Побои',
        awayTeamLogoUrl: 'images/teams/poboi.svg',
        awayTeamScore: 4,
        matchDateTime: '27 июня, 19:00',
        seasonYear: 2025,
        roundNumber: 2,
        venueName: 'Стадион «Трёхэтажка»',
    },
    {
        id: 5,
        homeTeamName: 'Шоркино',
        homeTeamLogoUrl: 'images/teams/shorkino.png',
        homeTeamScore: 0,
        awayTeamName: 'Побои',
        awayTeamLogoUrl: 'images/teams/poboi.svg',
        awayTeamScore: 1,
        matchDateTime: '28 июня, 18:00',
        seasonYear: 2025,
        roundNumber: 3,
        venueName: 'Стадион «Трёхэтажка»',
    },
    {
        id: 6,
        homeTeamName: 'Сятра',
        homeTeamLogoUrl: 'images/teams/sytra_logo.svg',
        homeTeamScore: 2,
        awayTeamName: 'Сарбаки',
        awayTeamLogoUrl: 'images/teams/sarbaki.svg',
        awayTeamScore: 3,
        matchDateTime: '28 июня, 19:00',
        seasonYear: 2025,
        roundNumber: 3,
        venueName: 'Стадион «Трёхэтажка»',
    },
    {
        id: 7,
        homeTeamName: 'Шоркино',
        homeTeamLogoUrl: 'images/teams/shorkino.png',
        homeTeamScore: 3,
        awayTeamName: 'Сятра',
        awayTeamLogoUrl: 'images/teams/sytra_logo.svg',
        awayTeamScore: 5,
        matchDateTime: '5 июля, 18:00',
        seasonYear: 2025,
        roundNumber: 4,
        venueName: 'Стадион «Трёхэтажка»',
    },
    {
        id: 8,
        homeTeamName: 'Побои',
        homeTeamLogoUrl: 'images/teams/poboi.svg',
        homeTeamScore: 4,
        awayTeamName: 'Сарбаки',
        awayTeamLogoUrl: 'images/teams/sarbaki.svg',
        awayTeamScore: 3,
        matchDateTime: '5 июля, 19:00',
        seasonYear: 2025,
        roundNumber: 4,
        venueName: 'Стадион «Трёхэтажка»',
    },
    {
        id: 9,
        homeTeamName: 'Побои',
        homeTeamLogoUrl: 'images/teams/poboi.svg',
        homeTeamScore: 4,
        awayTeamName: 'Сятра',
        awayTeamLogoUrl: 'images/teams/sytra_logo.svg',
        awayTeamScore: 3,
        matchDateTime: '12 июля, 18:00',
        seasonYear: 2025,
        roundNumber: 5,
        venueName: 'Стадион «Трёхэтажка»',
    },
    {
        id: 10,
        homeTeamName: 'Шоркино',
        homeTeamLogoUrl: 'images/teams/shorkino.png',
        homeTeamScore: 0,
        awayTeamName: 'Сарбаки',
        awayTeamLogoUrl: 'images/teams/sarbaki.svg',
        awayTeamScore: 1,
        matchDateTime: '12 июля, 19:00',
        seasonYear: 2025,
        roundNumber: 5,
        venueName: 'Стадион «Трёхэтажка»',
    },
    {
        id: 11,
        homeTeamName: 'Побои',
        homeTeamLogoUrl: 'images/teams/poboi.svg',
        homeTeamScore: null,
        awayTeamName: 'Шоркино',
        awayTeamLogoUrl: 'images/teams/shorkino.png',
        awayTeamScore: null,
        matchDateTime: '26 июля, 18:00',
        seasonYear: 2025,
        roundNumber: 6,
        venueName: 'Стадион «Трёхэтажка»',
    },
    {
        id: 12,
        homeTeamName: 'Сарбаки',
        homeTeamLogoUrl: 'images/teams/sarbaki.svg',
        homeTeamScore: null,
        awayTeamName: 'Сятра',
        awayTeamLogoUrl: 'images/teams/sytra_logo.svg',
        awayTeamScore: null,
        matchDateTime: '26 июля, 19:00',
        seasonYear: 2025,
        roundNumber: 6,
        venueName: 'Стадион «Трёхэтажка»',
    },
];
